<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net46</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.4.0</Version>
    <AssemblyVersion>1.4.0.0</AssemblyVersion>
    <FileVersion>1.4.0.0</FileVersion>
    <InformationalVersion>1.4.0</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Company>SubtitleFontHelper</Company>
    <Product>SubtitleFontHelper</Product>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="artifacts\**\*.cs" />
    <EmbeddedResource Remove="artifacts\**\*" />
    <None Remove="artifacts\**\*" />
    <Page Remove="artifacts\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
